# Schema for the configuration files of the Cancel Button module.

cancel_button.settings:
  type: config_object
  label: 'Cancel button settings'
  mapping:
    entity_type_cancel_destination:
      type: sequence
      label: 'Default (fallback) destination settings for the Cancel button on Entity forms'
      sequence:
          type: mapping
          label: 'Default settings for the cancel button'
          mapping:
            path:
              type: string
              label: 'The default path where the Cancel button will take users to, on entity forms for entity types without specific configuration'
            enabled:
              type: boolean
              label: 'Whether the cancel button is enabled for this entity type'
