filter_settings.filter_footnotes:
  type: filter
  label: 'Footnotes'
  mapping:
    footnotes_collapse:
      type: boolean
      label: 'Collapse footnotes with identical content'
    footnotes_css:
      type: boolean
      label: 'Use footnotes CSS'
    footnotes_dialog:
      type: boolean
      label: 'Open footnote references in a dialog'
    footnotes_footer_disable:
      type: boolean
      label: 'Disable output of the footnotes footer'

block.settings.footnotes_group:
  type: block_settings
  label: 'Footnotes Group block'
  mapping:
    group_via_js:
      type: boolean
      label: 'Group via JS'
