field.field_settings.yearonly:
  type: mapping
  label: 'Year Only range settings'
  mapping:
    yearonly_from:
      type: string
      label: 'Start year'
    yearonly_to:
      type: string
      label: 'End year'
